# Generated by Django 5.2.3 on 2025-07-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("audit_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modellogentry",
            name="public",
            field=models.BooleanField(
                default=True, help_text="This is a public log entry"
            ),
        ),
        migrations.AlterField(
            model_name="modellogentry",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Content type",
            ),
        ),
    ]
