# Generated by Django 4.2.8 on 2023-12-23 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conjunto", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LicensePage",
        ),
        migrations.DeleteModel(
            name="PrivacyPage",
        ),
        migrations.DeleteModel(
            name="StaticPage",
        ),
        migrations.DeleteModel(
            name="StaticVersionedPage",
        ),
    ]
