# Generated by Django 4.2.16 on 2024-09-07 11:39

from django.db import migrations, models
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("conjunto", "0003_add_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "version",
                    versionfield.fields.VersionField(default="1.0.0", unique=True),
                ),
            ],
            options={
                "verbose_name": "Privacy page",
                "verbose_name_plural": "Privacy pages",
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Internal name of the page. Leave empty of in doubt.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Static page",
                "verbose_name_plural": "Static pages",
            },
        ),
        migrations.CreateModel(
            name="TermsConditionsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "version",
                    versionfield.fields.VersionField(default="1.0.0", unique=True),
                ),
            ],
            options={
                "verbose_name": "Terms and conditions page",
                "verbose_name_plural": "Terms and conditions pages",
            },
        ),
    ]
