# Generated by Django 4.2.16 on 2024-12-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conjunto", "0004_privacypage_staticpage_termsconditionspage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrivacyPage",
        ),
        migrations.DeleteModel(
            name="StaticPage",
        ),
        migrations.DeleteModel(
            name="TermsConditionsPage",
        ),
    ]
