# Generated by Django 4.2.8 on 2023-12-29 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaticVersionedPage",
        ),
        migrations.AlterModelOptions(
            name="licensepage",
            options={
                "verbose_name": "License page",
                "verbose_name_plural": "License pages",
            },
        ),
        migrations.AlterModelOptions(
            name="privacypage",
            options={
                "verbose_name": "Privacy page",
                "verbose_name_plural": "Privacy pages",
            },
        ),
        migrations.AlterModelOptions(
            name="staticpage",
            options={
                "verbose_name": "Static page",
                "verbose_name_plural": "Static pages",
            },
        ),
    ]
