# Generated by Django 4.2.9 on 2024-01-29 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_delete_staticversionedpage_alter_licensepage_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LicensePage",
            new_name="TermsConditionsPage",
        ),
    ]
