# Generated by Django 4.2.9 on 2024-01-30 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_rename_licensepage_termsconditionspage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsconditionspage",
            options={
                "verbose_name": "Terms and conditions page",
                "verbose_name_plural": "Terms and conditions pages",
            },
        ),
    ]
