# Generated by Django 4.2.9 on 2024-02-06 07:37

from django.db import migrations
import versionfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_alter_termsconditionspage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacypage",
            name="version",
            field=versionfield.fields.VersionField(default="1.0.0", unique=True),
        ),
        migrations.AlterField(
            model_name="termsconditionspage",
            name="version",
            field=versionfield.fields.VersionField(default="1.0.0", unique=True),
        ),
    ]
