# Generated by Django 4.2.9 on 2024-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_alter_privacypage_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Internal name of the page. Leave empty of in doubt.",
                max_length=255,
                null=True,
            ),
        ),
    ]
